//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.17 at 12:20:36 PM IST 
//


package com.getusroi.paas.subnet.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubnetConfiguration" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SubnetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Vpc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Cidr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Environment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Acl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subnetConfiguration"
})
public class SubnetConfigurations
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SubnetConfiguration")
    protected List<SubnetConfiguration> subnetConfiguration;

    /**
     * Gets the value of the subnetConfiguration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subnetConfiguration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubnetConfiguration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubnetConfiguration }
     * 
     * 
     */
    public List<SubnetConfiguration> getSubnetConfiguration() {
        if (subnetConfiguration == null) {
            subnetConfiguration = new ArrayList<SubnetConfiguration>();
        }
        return this.subnetConfiguration;
    }

	public void setSubnetConfiguration(List<SubnetConfiguration> subnetConfiguration) {
		this.subnetConfiguration = subnetConfiguration;
	}

}
