//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.17 at 12:20:36 PM IST 
//


package com.getusroi.paas.subnet.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubnetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Vpc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cidr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Environment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Acl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subnetName",
    "vpc",
    "cidr",
    "environment",
    "acl"
})
public class SubnetConfiguration
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SubnetName", required = true)
    protected String subnetName;
    @XmlElement(name = "Vpc", required = true)
    protected String vpc;
    @XmlElement(name = "Cidr", required = true)
    protected String cidr;
    @XmlElement(name = "Environment", required = true)
    protected String environment;
    @XmlElement(name = "Acl", required = true)
    protected String acl;

    /**
     * Gets the value of the subnetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubnetName() {
        return subnetName;
    }

    /**
     * Sets the value of the subnetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubnetName(String value) {
        this.subnetName = value;
    }

    /**
     * Gets the value of the vpc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVpc() {
        return vpc;
    }

    /**
     * Sets the value of the vpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVpc(String value) {
        this.vpc = value;
    }

    /**
     * Gets the value of the cidr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCidr() {
        return cidr;
    }

    /**
     * Sets the value of the cidr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCidr(String value) {
        this.cidr = value;
    }

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironment(String value) {
        this.environment = value;
    }

    /**
     * Gets the value of the acl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcl() {
        return acl;
    }

    /**
     * Sets the value of the acl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcl(String value) {
        this.acl = value;
    }

}
