//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.17 at 12:02:02 PM IST 
//


package com.getusroi.paas.vpc.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VPCName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cidr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Acl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vpcName",
    "cidr",
    "acl"
})
public class AddVirtualPrivateCloudConfig
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "VPCName", required = true)
    protected String vpcName;
    @XmlElement(name = "Cidr", required = true)
    protected String cidr;
    @XmlElement(name = "Acl", required = true)
    protected String acl;

    /**
     * Gets the value of the vpcName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVPCName() {
        return vpcName;
    }

    /**
     * Sets the value of the vpcName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVPCName(String value) {
        this.vpcName = value;
    }

    /**
     * Gets the value of the cidr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCidr() {
        return cidr;
    }

    /**
     * Sets the value of the cidr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCidr(String value) {
        this.cidr = value;
    }

    /**
     * Gets the value of the acl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcl() {
        return acl;
    }

    /**
     * Sets the value of the acl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcl(String value) {
        this.acl = value;
    }

}
