//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 11:55:29 AM IST 
//


package com.getusroi.paas.application.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NetworkConfig">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="vpcName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="subnetName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ImageRegistryConfig">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ServiceConfig">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Service">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="instanceCount" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ImageRegistry">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="repository" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RunSettings">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="runCommand" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="hostName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="NetworkPolicy">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="portType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="hostPort" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="containerPort" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="HealthCheckRoute">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="typeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="nterval" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="threshold" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="ignore" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Volume" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="Subnet">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="subnetName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="cidr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="applicationName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "networkConfig",
    "imageRegistryConfig",
    "serviceConfig"
})
public class ApplicationConfig
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "NetworkConfig", required = true)
    protected NetworkConfig networkConfig;
    @XmlElement(name = "ImageRegistryConfig", required = true)
    protected ImageRegistryConfig imageRegistryConfig;
    @XmlElement(name = "ServiceConfig", required = true)
    protected ServiceConfig serviceConfig;
    @XmlAttribute(name = "applicationName")
    protected String applicationName;

    /**
     * Gets the value of the networkConfig property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkConfig }
     *     
     */
    public NetworkConfig getNetworkConfig() {
        return networkConfig;
    }

    /**
     * Sets the value of the networkConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkConfig }
     *     
     */
    public void setNetworkConfig(NetworkConfig value) {
        this.networkConfig = value;
    }

    /**
     * Gets the value of the imageRegistryConfig property.
     * 
     * @return
     *     possible object is
     *     {@link ImageRegistryConfig }
     *     
     */
    public ImageRegistryConfig getImageRegistryConfig() {
        return imageRegistryConfig;
    }

    /**
     * Sets the value of the imageRegistryConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageRegistryConfig }
     *     
     */
    public void setImageRegistryConfig(ImageRegistryConfig value) {
        this.imageRegistryConfig = value;
    }

    /**
     * Gets the value of the serviceConfig property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceConfig }
     *     
     */
    public ServiceConfig getServiceConfig() {
        return serviceConfig;
    }

    /**
     * Sets the value of the serviceConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceConfig }
     *     
     */
    public void setServiceConfig(ServiceConfig value) {
        this.serviceConfig = value;
    }

    /**
     * Gets the value of the applicationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * Sets the value of the applicationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationName(String value) {
        this.applicationName = value;
    }

}
