//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 11:55:29 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://getusroi.com/internal/integration-fwk-Supporting")
package com.getusroi.paas.application.jaxb;
