//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 11:55:29 AM IST 
//


package com.getusroi.paas.application.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Service">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="instanceCount" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ImageRegistry">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="repository" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RunSettings">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="runCommand" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="hostName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NetworkPolicy">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="portType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="hostPort" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="containerPort" type="{http://www.w3.org/2001/XMLSchema}short" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="HealthCheckRoute">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="typeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nterval" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="threshold" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="ignore" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Volume" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="Subnet">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="subnetName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="cidr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "service",
    "imageRegistry",
    "runSettings",
    "networkPolicy",
    "healthCheckRoute",
    "volume",
    "subnet"
})
public class ServiceConfig
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Service", required = true)
    protected Service service;
    @XmlElement(name = "ImageRegistry", required = true)
    protected ImageRegistry imageRegistry;
    @XmlElement(name = "RunSettings", required = true)
    protected RunSettings runSettings;
    @XmlElement(name = "NetworkPolicy", required = true)
    protected NetworkPolicy networkPolicy;
    @XmlElement(name = "HealthCheckRoute", required = true)
    protected HealthCheckRoute healthCheckRoute;
    @XmlElement(name = "Volume")
    protected short volume;
    @XmlElement(name = "Subnet", required = true)
    protected Subnet subnet;

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link Service }
     *     
     */
    public Service getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link Service }
     *     
     */
    public void setService(Service value) {
        this.service = value;
    }

    /**
     * Gets the value of the imageRegistry property.
     * 
     * @return
     *     possible object is
     *     {@link ImageRegistry }
     *     
     */
    public ImageRegistry getImageRegistry() {
        return imageRegistry;
    }

    /**
     * Sets the value of the imageRegistry property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageRegistry }
     *     
     */
    public void setImageRegistry(ImageRegistry value) {
        this.imageRegistry = value;
    }

    /**
     * Gets the value of the runSettings property.
     * 
     * @return
     *     possible object is
     *     {@link RunSettings }
     *     
     */
    public RunSettings getRunSettings() {
        return runSettings;
    }

    /**
     * Sets the value of the runSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunSettings }
     *     
     */
    public void setRunSettings(RunSettings value) {
        this.runSettings = value;
    }

    /**
     * Gets the value of the networkPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkPolicy }
     *     
     */
    public NetworkPolicy getNetworkPolicy() {
        return networkPolicy;
    }

    /**
     * Sets the value of the networkPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkPolicy }
     *     
     */
    public void setNetworkPolicy(NetworkPolicy value) {
        this.networkPolicy = value;
    }

    /**
     * Gets the value of the healthCheckRoute property.
     * 
     * @return
     *     possible object is
     *     {@link HealthCheckRoute }
     *     
     */
    public HealthCheckRoute getHealthCheckRoute() {
        return healthCheckRoute;
    }

    /**
     * Sets the value of the healthCheckRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthCheckRoute }
     *     
     */
    public void setHealthCheckRoute(HealthCheckRoute value) {
        this.healthCheckRoute = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     */
    public short getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     */
    public void setVolume(short value) {
        this.volume = value;
    }

    /**
     * Gets the value of the subnet property.
     * 
     * @return
     *     possible object is
     *     {@link Subnet }
     *     
     */
    public Subnet getSubnet() {
        return subnet;
    }

    /**
     * Sets the value of the subnet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subnet }
     *     
     */
    public void setSubnet(Subnet value) {
        this.subnet = value;
    }

}
